spring.application.name=online-course-bff

# ==============================================================================
# 1. CONEXION A BASE DE DATOS ORACLE CLOUD
# ==============================================================================
# Usamos variables de entorno para que el sistema (Windows o Linux) defina la ruta y el URL
spring.datasource.url=${DB_URL:jdbc:oracle:thin:@bzb80ilr1f18orsy_high}
oracle.net.tns_admin=${TNS_ADMIN_PATH:./Wallet}
spring.datasource.username=ADMIN
spring.datasource.password=Renemaria1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Configuracion de Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# 2. CONFIGURACION RABBITMQ
# ==========================================
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.username=${RABBIT_USER:guest}
spring.rabbitmq.password=${RABBIT_PASS:guest}
app.queue.normal=cola_normal_cursos
app.queue.error=cola_errores_cursos

# ==========================================
# 3. AWS S3
# ==========================================
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=eu-west-1
cloud.aws.s3.bucket=${AWS_BUCKET_NAME:bucket-temporal}

# ==========================================
# 4. AZURE AD B2C
# ==========================================
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWK_URI}